array_width = 140
attr_fn_like_width = 140
binop_separator = "Back"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 3
brace_style = "PreferSameLine"
chain_width = 120
color = "Auto"
combine_control_expr = true
comment_width = 120
condense_wildcard_suffixes = true
control_brace_style = "AlwaysSameLine"
disable_all_formatting = false
edition = "2024"
empty_item_single_line = true
enum_discrim_align_threshold = 32
error_on_line_overflow = true
error_on_unformatted = false
fn_call_width = 140
fn_params_layout = "Tall"
fn_single_line = true
force_explicit_abi = true
force_multiline_blocks = false
format_code_in_doc_comments = false
doc_comment_code_block_width = 120
format_generated_files = true
format_macro_bodies = false
format_macro_matchers = false
format_strings = false
generated_marker_line_search_limit = 5
group_imports = "StdExternalCrate"
hard_tabs = false
hex_literal_case = "Lower"
imports_granularity = "Item"
imports_indent = "Block"
imports_layout = "Mixed"
indent_style = "Block"
inline_attribute_width = 120
match_arm_blocks = true
match_arm_leading_pipes = "Always"
match_block_trailing_comma = true
max_width = 160
merge_derives = true
newline_style = "Auto"
normalize_comments = false
normalize_doc_attributes = true
overflow_delimited_expr = true
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
short_array_element_width_threshold = 40
show_parse_errors = true
single_line_if_else_max_width = 140
single_line_let_else_max_width = 140
skip_children = false
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_field_align_threshold = 32
struct_lit_single_line = true
struct_lit_width = 120
struct_variant_width = 120
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Compressed"
use_field_init_shorthand = true
use_small_heuristics = "Default"
use_try_shorthand = true
where_single_line = true
wrap_comments = true
