[build]
incremental     = false
rustdocflags = [
#    "-Z", "unstable-options", "--show-coverage",
    "--cfg", "feature=\"docsrs\"",
    "--check-cfg", "`cfg(feature, values(\"docsrs\"))`",
    "--check-cfg", "`cfg(coverage_nightly)`",
    "--check-cfg", "`cfg(feature, values(\"dummy_doc_images_feature\"))`",
]

rustflags = [
    "--check-cfg", "`cfg(feature, values(\"docsrs\"))`",
    "--check-cfg", "`cfg(coverage_nightly)`",
    "--check-cfg", "`cfg(feature, values(\"dummy_doc_images_feature\"))`",
    # "-C", "link-args=-fuse-ld=lld",
    "-Dabsolute_paths_not_starting_with_crate",
    "-Delided-lifetimes-in-paths",
    "-Wdead_code",
    "-Wexplicit_outlives_requirements",
    "-Wfuture_incompatible",
    # "-Dfuzzy_provenance_casts",
    "-Dkeyword_idents",
    "-Wlet_underscore_drop",
    # "-Dlossy_provenance_casts",
    "-Dmacro_use_extern_crate",
    "-Wmeta_variable_misuse",
    "-Wmissing_copy_implementations",
    "-Wmissing_debug_implementations",
    "-Wnon_ascii_idents",
    # "-Wnon_exhaustive_omitted_patterns",
    "-Wnonstandard_style",
    "-Wrust_2018_idioms",
    "-Wrust_2021_prefixes_incompatible_syntax",
    "-Wtrivial_casts",
    # "-Wunnameable_types",
    "-Aunreachable_pub",
    "-Dtrivial_numeric_casts",
    "-Dunsafe_code",
    "-Wunused",
    # "-Wunused_crate_dependencies",
    "-Dunused_extern_crates",
    "-Dunused_import_braces",
    "-Wunused_lifetimes",
    "-Wunused_macro_rules",
    "-Aunused_qualifications",
    "-Wclippy::style",
    "-Wclippy::pedantic",
    "-Aclippy::restriction",
    "-Aclippy::missing_errors_doc",
    "-Aclippy::missing_panics_doc",
    "-Aclippy::module_name_repetitions",
# Restriction lints for Rust + Clippy 1.65
    "-Wclippy::alloc_instead_of_core",
    "-Wclippy::allow_attributes_without_reason",
    "-Aclippy::arithmetic_side_effects",
    "-Aclippy::as_conversions",
    "-Wclippy::as_underscore",
    "-Wclippy::assertions_on_result_states",
    "-Wclippy::box_default",
    "-Wclippy::clone_on_ref_ptr",
    "-Dclippy::create_dir",
    "-Dclippy::default_union_representation",
    "-Wclippy::deref_by_slicing",
    "-Dclippy::disallowed_script_idents",
    "-Aclippy::else_if_without_else",
    "-Wclippy::empty_drop",
    "-Wclippy::empty_structs_with_brackets",
    "-Aclippy::exhaustive_enums",
    "-Aclippy::exhaustive_structs",
    "-Wclippy::exit",
    "-Wclippy::expect_used",
    "-Wclippy::filetype_is_file",
    "-Dclippy::float_cmp_const",
    "-Dclippy::fn_to_numeric_cast_any",
    "-Wclippy::format_push_string",
    "-Wclippy::get_unwrap",
    "-Wclippy::if_then_some_else_none",
    "-Aclippy::implicit_return",
    "-Dclippy::indexing_slicing",
    "-Wclippy::integer_division",
    "-Wclippy::let_and_return",
    "-Wclippy::lossy_float_literal",
    "-Aclippy::map_err_ignore",
    "-Dclippy::mem_forget",
    "-Aclippy::missing_docs_in_private_items",
    "-Wclippy::missing_enforced_import_renames",
    "-Aclippy::missing_inline_in_public_items",
    "-Wclippy::mixed_read_write_in_expression",
    "-Aclippy::mod_module_files",
    "-Aclippy::modulo_arithmetic",
    "-Wclippy::multiple_inherent_impl",
    "-Aclippy::non_ascii_literal",
    "-Wclippy::panic",
    "-Wclippy::panic_in_result_fn",
#    "-Dclippy::partial_pub_fields",
    "-Aclippy::pattern_type_mismatch",
    "-Wclippy::print_stderr",
    "-Wclippy::print_stdout",
    "-Wclippy::rc_buffer",
    "-Dclippy::rc_mutex",
    "-Wclippy::rest_pat_in_fully_bound_structs",
    "-Wclippy::same_name_method",
    "-Aclippy::self_named_module_files",
#    "-Wclippy::semicolon_inside_block",
#    "-Aclippy::semicolon_outside_block",
    "-Aclippy::separated_literal_suffix",
    "-Aclippy::shadow_reuse",
    "-Aclippy::shadow_same",
    "-Aclippy::shadow_unrelated",
    "-Aclippy::single_char_lifetime_names",
    "-Wclippy::std_instead_of_alloc",
    "-Wclippy::std_instead_of_core",
    "-Wclippy::str_to_string",
    "-Aclippy::string_add",
    "-Wclippy::string_slice",
    "-Wclippy::string_to_string",
#    "-Wclippy::suspicious_xor_used_as_pow",
    "-Aclippy::todo",
    "-Aclippy::try_err",
    "-Wclippy::undocumented_unsafe_blocks",
    "-Aclippy::unimplemented",
    "-Wclippy::unnecessary_safety_comment",
#    "-Wclippy::unnecessary_safety_doc",
    "-Wclippy::unnecessary_self_imports",
    "-Wclippy::unneeded_field_pattern",
    "-Aclippy::unreachable",
    "-Wclippy::unseparated_literal_suffix",
    "-Wclippy::unwrap_in_result",
    "-Wclippy::unwrap_used",
    "-Aclippy::use_debug",
    "-Wclippy::verbose_file_reads",
    "-Aclippy::wildcard_enum_match_arm",
]
[target.'cfg(all())']
